"""Seed data for IRCC immigration programs."""

PROGRAMS_SEED = [
    {
        "code": "express_entry_fsw",
        "name": "Federal Skilled Worker Program (FSWP)",
        "category": "Express Entry",
        "description": "Programme pour les travailleurs qualifiés avec expérience professionnelle étrangère. Basé sur le système de points (67/100 minimum).",
        "processing_time_days": 180,
        "government_fee": 1365.0,
        "documents_required": "Passeport;Résultats test de langue (IELTS/TEF);Évaluation des diplômes (ECA);Lettres d'emploi;Relevés bancaires;Certificat de police;Examen médical;Photos;CV détaillé",
        "eligibility_criteria": "Minimum 1 an d'expérience continue à temps plein (ou équivalent);Niveau CLB 7 minimum en langues;Éducation post-secondaire avec ECA;67 points sur la grille FSW",
    },
    {
        "code": "express_entry_cec",
        "name": "Canadian Experience Class (CEC)",
        "category": "Express Entry",
        "description": "Programme pour les personnes ayant déjà une expérience de travail qualifié au Canada.",
        "processing_time_days": 180,
        "government_fee": 1365.0,
        "documents_required": "Passeport;Résultats test de langue (IELTS/TEF);Lettres d'emploi canadien;Relevés de paie;T4;Certificat de police;Examen médical;Photos",
        "eligibility_criteria": "12 mois d'expérience de travail qualifié au Canada dans les 3 dernières années;CLB 7 pour NOC TEER 0/1, CLB 5 pour NOC TEER 2/3;Pas d'intention de résider au Québec",
    },
    {
        "code": "express_entry_fst",
        "name": "Federal Skilled Trades Program (FSTP)",
        "category": "Express Entry",
        "description": "Programme pour les travailleurs de métiers spécialisés qualifiés.",
        "processing_time_days": 180,
        "government_fee": 1365.0,
        "documents_required": "Passeport;Résultats test de langue;Certificat de qualification professionnelle;Lettres d'emploi;Certificat de police;Examen médical;Photos",
        "eligibility_criteria": "2 ans d'expérience à temps plein dans un métier spécialisé;Offre d'emploi valide ou certificat de qualification canadien;CLB 5 oral, CLB 4 écrit",
    },
    {
        "code": "pnp",
        "name": "Programme des Nominés Provinciaux (PNP)",
        "category": "PNP",
        "description": "Programmes provinciaux/territoriaux permettant aux provinces de nommer des immigrants répondant à leurs besoins.",
        "processing_time_days": 330,
        "government_fee": 1365.0,
        "documents_required": "Passeport;Résultats test de langue;Évaluation des diplômes;Lettres d'emploi;Lettre de nomination provinciale;Certificat de police;Examen médical;Photos;Documents spécifiques à la province",
        "eligibility_criteria": "Critères variables selon la province et le stream;Nomination officielle de la province;Intention de résider dans la province",
    },
    {
        "code": "iec_working_holiday",
        "name": "International Experience Canada - Working Holiday (PVT)",
        "category": "IEC",
        "description": "Permis de travail ouvert pour les jeunes de pays partenaires.",
        "processing_time_days": 56,
        "government_fee": 346.0,
        "documents_required": "Passeport valide;Preuve de fonds (CAD 2500);Assurance maladie;Certificat de police;CV;Photo numérique",
        "eligibility_criteria": "18-35 ans (selon le pays);Citoyenneté d'un pays partenaire;Pas de personnes à charge;Billet retour ou fonds suffisants",
    },
    {
        "code": "iec_young_professionals",
        "name": "International Experience Canada - Young Professionals",
        "category": "IEC",
        "description": "Permis de travail lié à un employeur pour les jeunes professionnels.",
        "processing_time_days": 56,
        "government_fee": 346.0,
        "documents_required": "Passeport valide;Offre d'emploi;Contrat de travail;Preuve de fonds;Assurance maladie;Certificat de police;CV;Diplômes",
        "eligibility_criteria": "18-35 ans;Offre d'emploi qualifié au Canada;Emploi lié au domaine d'études/expérience",
    },
    {
        "code": "iec_coop",
        "name": "International Experience Canada - Stage/Co-op",
        "category": "IEC",
        "description": "Permis de travail pour stage dans le cadre d'un programme d'études.",
        "processing_time_days": 56,
        "government_fee": 346.0,
        "documents_required": "Passeport valide;Lettre d'acceptation de stage;Convention de stage;Preuve inscription programme d'études;Assurance maladie;Certificat de police",
        "eligibility_criteria": "18-35 ans;Inscrit dans un établissement d'enseignement;Stage requis pour le programme d'études",
    },
    {
        "code": "study_permit",
        "name": "Permis d'études",
        "category": "Études",
        "description": "Permis pour étudier dans un établissement d'enseignement désigné (DLI) au Canada.",
        "processing_time_days": 60,
        "government_fee": 150.0,
        "documents_required": "Passeport;Lettre d'acceptation (DLI);Provincial Attestation Letter (PAL);Preuve de fonds;Relevés bancaires 4 mois;Certificat de police;Examen médical;Photos;Relevés de notes;Diplômes",
        "eligibility_criteria": "Acceptation dans un DLI;PAL de la province;Preuve de fonds suffisants (tuition + CAD 20,635/an);Pas de casier judiciaire;Bonne santé",
    },
    {
        "code": "work_permit_lmia",
        "name": "Permis de travail (LMIA)",
        "category": "Travail",
        "description": "Permis de travail nécessitant une Étude d'Impact sur le Marché du Travail (EIMT/LMIA).",
        "processing_time_days": 90,
        "government_fee": 155.0,
        "documents_required": "Passeport;LMIA positive;Offre d'emploi;Contrat de travail;CV;Diplômes;Lettres d'expérience;Certificat de police;Examen médical;Photos",
        "eligibility_criteria": "LMIA positive de l'employeur;Qualifications pour le poste;Intention de quitter le Canada à l'expiration",
    },
    {
        "code": "work_permit_imp",
        "name": "Permis de travail (Mobilité internationale - sans LMIA)",
        "category": "Travail",
        "description": "Permis de travail exempt de LMIA sous le Programme de Mobilité Internationale.",
        "processing_time_days": 60,
        "government_fee": 255.0,
        "documents_required": "Passeport;Offre d'emploi;Numéro d'offre du Portail employeur;CV;Diplômes;Lettres d'expérience;Certificat de police;Photos",
        "eligibility_criteria": "Catégorie IMP applicable (transfert intra-entreprise, CUSMA, mobilité francophone, etc.);Offre d'emploi valide",
    },
    {
        "code": "family_spouse",
        "name": "Parrainage de conjoint/partenaire",
        "category": "Famille",
        "description": "Parrainage d'un époux, conjoint de fait ou partenaire conjugal.",
        "processing_time_days": 365,
        "government_fee": 1365.0,
        "documents_required": "Passeport des deux;Certificat de mariage/union;Preuves de relation (photos, communications, voyages);Formulaire IMM 5532;Déclaration de garant;Certificat de police;Examen médical;Photos",
        "eligibility_criteria": "Garant citoyen canadien ou RP;18 ans minimum;Relation authentique;Engagement de 3 ans;Pas de parrainage antérieur dans les 5 ans",
    },
    {
        "code": "family_parent",
        "name": "Parrainage de parents et grands-parents",
        "category": "Famille",
        "description": "Programme d'invitation pour parrainer ses parents ou grands-parents.",
        "processing_time_days": 540,
        "government_fee": 1365.0,
        "documents_required": "Passeport;Preuves de lien familial;Avis de cotisation (3 ans);Preuve de revenu minimum;Engagement de 20 ans;Certificat de police;Examen médical;Photos",
        "eligibility_criteria": "Garant citoyen canadien ou RP;Revenu minimum vital (3 années consécutives);Invitation sélectionnée;Engagement financier de 20 ans",
    },
    {
        "code": "family_child",
        "name": "Parrainage d'enfant à charge",
        "category": "Famille",
        "description": "Parrainage d'un enfant à charge pour la résidence permanente.",
        "processing_time_days": 365,
        "government_fee": 365.0,
        "documents_required": "Passeport de l'enfant;Certificat de naissance;Preuves de garde/autorité parentale;Certificat de police (si 18+);Examen médical;Photos",
        "eligibility_criteria": "Enfant de moins de 22 ans;Pas marié/en union;Dépendant financièrement du parent",
    },
    {
        "code": "super_visa",
        "name": "Super Visa (parents/grands-parents)",
        "category": "Famille",
        "description": "Visa multi-entrées permettant des séjours jusqu'à 5 ans par visite.",
        "processing_time_days": 90,
        "government_fee": 100.0,
        "documents_required": "Passeport;Lettre d'invitation de l'enfant/petit-enfant;Preuve de revenu de l'hôte;Assurance maladie (1 an minimum, CAD 100K);Preuve de lien familial;Examen médical;Photos",
        "eligibility_criteria": "Parent ou grand-parent d'un citoyen/RP canadien;Assurance maladie valide;Examen médical réussi;Hôte au-dessus du seuil de revenu",
    },
    {
        "code": "visitor_visa",
        "name": "Visa de résident temporaire (visiteur)",
        "category": "Temporaire",
        "description": "Visa pour visiter le Canada en tant que touriste ou pour affaires.",
        "processing_time_days": 30,
        "government_fee": 100.0,
        "documents_required": "Passeport;Photos;Preuve de fonds;Lettre d'invitation (si applicable);Itinéraire de voyage;Preuve d'attaches au pays d'origine;Relevés bancaires;Lettre d'emploi",
        "eligibility_criteria": "Documents de voyage valides;Bonne santé;Pas de casier judiciaire;Prouver l'intention de quitter le Canada;Fonds suffisants",
    },
    {
        "code": "refugee",
        "name": "Programme de réfugiés",
        "category": "Réfugiés",
        "description": "Protection pour les personnes persécutées ou en danger dans leur pays d'origine.",
        "processing_time_days": 365,
        "government_fee": 0.0,
        "documents_required": "Documents d'identité disponibles;Formulaire de demande d'asile;Déclaration personnelle;Preuves de persécution;Rapports de pays;Documents de voyage (si disponibles)",
        "eligibility_criteria": "Crainte fondée de persécution;Ne peut retourner dans son pays;Référé par le HCR ou parrainage privé;Ou demande d'asile à l'arrivée au Canada",
    },
]
