"""Seed data for IMM checklists per program."""

REQUIREMENTS_SEED = {
    "express_entry_fsw": [
        {
            "document_type": "identity",
            "document_name": "Passeport valide",
            "description": "Copie de toutes les pages du passeport (incluant pages vierges)",
            "priority": "mandatory",
            "imm_form_reference": "IMM 5690",
            "sort_order": 1,
        },
        {
            "document_type": "identity",
            "document_name": "Photos d'identité",
            "description": "2 photos conformes aux spécifications IRCC (35mm x 45mm)",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 2,
        },
        {
            "document_type": "language",
            "document_name": "Résultats test de langue (principal)",
            "description": "IELTS General ou TEF/TCF Canada - moins de 2 ans",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 3,
        },
        {
            "document_type": "language",
            "document_name": "Résultats test de langue (secondaire)",
            "description": "Test pour la 2e langue officielle (optionnel, points bonus)",
            "priority": "optional",
            "imm_form_reference": None,
            "sort_order": 4,
        },
        {
            "document_type": "education",
            "document_name": "Évaluation des diplômes (ECA/WES)",
            "description": "Rapport d'évaluation des diplômes étrangers par un organisme désigné",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 5,
        },
        {
            "document_type": "education",
            "document_name": "Diplômes et relevés de notes",
            "description": "Copies certifiées des diplômes et relevés de notes",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 6,
        },
        {
            "document_type": "employment",
            "document_name": "Lettres d'emploi",
            "description": "Lettres de tous les employeurs des 10 dernières années (poste, dates, heures/semaine, salaire)",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 7,
        },
        {
            "document_type": "employment",
            "document_name": "CV détaillé",
            "description": "CV complet sans lacunes, format chronologique",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 8,
        },
        {
            "document_type": "financial",
            "document_name": "Preuve de fonds",
            "description": "Relevés bancaires des 6 derniers mois montrant les fonds suffisants selon le tableau IRCC",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 9,
        },
        {
            "document_type": "security",
            "document_name": "Certificat de police",
            "description": "De chaque pays où vous avez vécu 6+ mois depuis l'âge de 18 ans",
            "priority": "mandatory",
            "imm_form_reference": "IMM 5690",
            "sort_order": 10,
        },
        {
            "document_type": "medical",
            "document_name": "Examen médical (IMM)",
            "description": "Par un médecin désigné (panel physician). Valide 12 mois.",
            "priority": "mandatory",
            "imm_form_reference": "IMM 1017",
            "sort_order": 11,
        },
        {
            "document_type": "form",
            "document_name": "Formulaire IMM 0008 - Demande de résidence permanente",
            "description": "Formulaire générique de demande RP",
            "priority": "mandatory",
            "imm_form_reference": "IMM 0008",
            "sort_order": 12,
        },
        {
            "document_type": "form",
            "document_name": "Annexe 1 - Antécédents/Déclaration",
            "description": "Historique des adresses, emplois, études",
            "priority": "mandatory",
            "imm_form_reference": "IMM 5669",
            "sort_order": 13,
        },
    ],
    "express_entry_cec": [
        {
            "document_type": "identity",
            "document_name": "Passeport valide",
            "description": "Copie de toutes les pages du passeport",
            "priority": "mandatory",
            "imm_form_reference": "IMM 5690",
            "sort_order": 1,
        },
        {
            "document_type": "language",
            "document_name": "Résultats test de langue",
            "description": "IELTS General ou TEF/TCF Canada - moins de 2 ans. CLB 7 pour TEER 0/1, CLB 5 pour TEER 2/3",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 2,
        },
        {
            "document_type": "employment",
            "document_name": "Lettres d'emploi canadien",
            "description": "Lettre(s) de l'employeur canadien confirmant poste, durée, heures, NOC",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 3,
        },
        {
            "document_type": "employment",
            "document_name": "Relevés de paie / T4",
            "description": "Preuves de revenu au Canada (T4, relevés de paie)",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 4,
        },
        {
            "document_type": "employment",
            "document_name": "Permis de travail",
            "description": "Copie du permis de travail ayant autorisé l'emploi au Canada",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 5,
        },
        {
            "document_type": "security",
            "document_name": "Certificat de police",
            "description": "De chaque pays où vous avez vécu 6+ mois depuis l'âge de 18 ans",
            "priority": "mandatory",
            "imm_form_reference": "IMM 5690",
            "sort_order": 6,
        },
        {
            "document_type": "medical",
            "document_name": "Examen médical",
            "description": "Par un médecin désigné",
            "priority": "mandatory",
            "imm_form_reference": "IMM 1017",
            "sort_order": 7,
        },
        {
            "document_type": "identity",
            "document_name": "Photos d'identité",
            "description": "2 photos conformes IRCC",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 8,
        },
    ],
    "study_permit": [
        {
            "document_type": "identity",
            "document_name": "Passeport valide",
            "description": "Valide pour toute la durée des études prévues",
            "priority": "mandatory",
            "imm_form_reference": "IMM 1294",
            "sort_order": 1,
        },
        {
            "document_type": "education",
            "document_name": "Lettre d'acceptation (LOA)",
            "description": "Lettre d'acceptation d'un établissement d'enseignement désigné (DLI)",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 2,
        },
        {
            "document_type": "education",
            "document_name": "Provincial Attestation Letter (PAL)",
            "description": "Lettre d'attestation provinciale (requise depuis janvier 2024)",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 3,
        },
        {
            "document_type": "financial",
            "document_name": "Preuve de fonds",
            "description": "Frais de scolarité + CAD 20,635/an pour frais de subsistance (relevés bancaires 4 mois)",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 4,
        },
        {
            "document_type": "education",
            "document_name": "Relevés de notes et diplômes",
            "description": "Relevés de notes des études précédentes",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 5,
        },
        {
            "document_type": "identity",
            "document_name": "Photos d'identité",
            "description": "2 photos conformes IRCC",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 6,
        },
        {
            "document_type": "security",
            "document_name": "Certificat de police",
            "description": "Si requis selon le pays de résidence",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 7,
        },
        {
            "document_type": "medical",
            "document_name": "Examen médical",
            "description": "Requis si études > 6 mois et provenance de certains pays",
            "priority": "recommended",
            "imm_form_reference": "IMM 1017",
            "sort_order": 8,
        },
        {
            "document_type": "form",
            "document_name": "Formulaire IMM 1294",
            "description": "Demande de permis d'études",
            "priority": "mandatory",
            "imm_form_reference": "IMM 1294",
            "sort_order": 9,
        },
        {
            "document_type": "other",
            "document_name": "Lettre d'explication / Plan d'études",
            "description": "Lettre expliquant le choix du programme et l'intention de retour",
            "priority": "recommended",
            "imm_form_reference": None,
            "sort_order": 10,
        },
    ],
    "work_permit_lmia": [
        {
            "document_type": "identity",
            "document_name": "Passeport valide",
            "description": "Valide pour toute la durée du permis de travail",
            "priority": "mandatory",
            "imm_form_reference": "IMM 1295",
            "sort_order": 1,
        },
        {
            "document_type": "employment",
            "document_name": "LMIA positive",
            "description": "Copie de la LMIA positive émise à l'employeur (numéro de confirmation)",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 2,
        },
        {
            "document_type": "employment",
            "document_name": "Offre d'emploi / Contrat",
            "description": "Offre d'emploi détaillée conforme à la LMIA",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 3,
        },
        {
            "document_type": "employment",
            "document_name": "CV et lettres d'expérience",
            "description": "CV détaillé + lettres des employeurs précédents",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 4,
        },
        {
            "document_type": "education",
            "document_name": "Diplômes",
            "description": "Copies des diplômes pertinents pour le poste",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 5,
        },
        {
            "document_type": "security",
            "document_name": "Certificat de police",
            "description": "De chaque pays où vous avez vécu 6+ mois",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 6,
        },
        {
            "document_type": "medical",
            "document_name": "Examen médical",
            "description": "Si requis selon le poste ou le pays",
            "priority": "recommended",
            "imm_form_reference": "IMM 1017",
            "sort_order": 7,
        },
        {
            "document_type": "identity",
            "document_name": "Photos d'identité",
            "description": "2 photos conformes IRCC",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 8,
        },
        {
            "document_type": "form",
            "document_name": "Formulaire IMM 1295",
            "description": "Demande de permis de travail",
            "priority": "mandatory",
            "imm_form_reference": "IMM 1295",
            "sort_order": 9,
        },
    ],
    "family_spouse": [
        {
            "document_type": "identity",
            "document_name": "Passeport du demandeur principal",
            "description": "Copie complète du passeport du conjoint parrainé",
            "priority": "mandatory",
            "imm_form_reference": "IMM 0008",
            "sort_order": 1,
        },
        {
            "document_type": "identity",
            "document_name": "Passeport du garant",
            "description": "Copie du passeport ou carte de citoyenneté/RP du garant",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 2,
        },
        {
            "document_type": "civil_status",
            "document_name": "Certificat de mariage",
            "description": "Certificat de mariage officiel ou preuve d'union de fait (12 mois)",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 3,
        },
        {
            "document_type": "relationship",
            "document_name": "Preuves de relation authentique",
            "description": "Photos ensemble, communications, voyages, comptes conjoints, bail commun",
            "priority": "mandatory",
            "imm_form_reference": "IMM 5532",
            "sort_order": 4,
        },
        {
            "document_type": "form",
            "document_name": "Formulaire IMM 5532 - Relation",
            "description": "Questionnaire sur la relation avec le partenaire",
            "priority": "mandatory",
            "imm_form_reference": "IMM 5532",
            "sort_order": 5,
        },
        {
            "document_type": "form",
            "document_name": "Formulaire IMM 1344 - Engagement",
            "description": "Engagement du garant et évaluation de la capacité financière",
            "priority": "mandatory",
            "imm_form_reference": "IMM 1344",
            "sort_order": 6,
        },
        {
            "document_type": "financial",
            "document_name": "Preuves financières du garant",
            "description": "Avis de cotisation, T4, relevés de paie du garant",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 7,
        },
        {
            "document_type": "security",
            "document_name": "Certificats de police",
            "description": "Pour le demandeur principal et les personnes à charge 18+",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 8,
        },
        {
            "document_type": "medical",
            "document_name": "Examen médical",
            "description": "Pour le demandeur principal et toutes les personnes à charge",
            "priority": "mandatory",
            "imm_form_reference": "IMM 1017",
            "sort_order": 9,
        },
        {
            "document_type": "identity",
            "document_name": "Photos d'identité",
            "description": "Du demandeur et des personnes à charge",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 10,
        },
        {
            "document_type": "form",
            "document_name": "Annexe A - Antécédents",
            "description": "Historique résidentiel, emploi, études du demandeur",
            "priority": "mandatory",
            "imm_form_reference": "IMM 5669",
            "sort_order": 11,
        },
    ],
    "visitor_visa": [
        {
            "document_type": "identity",
            "document_name": "Passeport valide",
            "description": "Valide au moins 6 mois après la date prévue de départ du Canada",
            "priority": "mandatory",
            "imm_form_reference": "IMM 5257",
            "sort_order": 1,
        },
        {
            "document_type": "identity",
            "document_name": "Photos d'identité",
            "description": "2 photos conformes IRCC",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 2,
        },
        {
            "document_type": "financial",
            "document_name": "Preuve de fonds",
            "description": "Relevés bancaires récents montrant des fonds suffisants pour le séjour",
            "priority": "mandatory",
            "imm_form_reference": None,
            "sort_order": 3,
        },
        {
            "document_type": "employment",
            "document_name": "Lettre d'emploi",
            "description": "Lettre de l'employeur confirmant le poste, salaire et congé approuvé",
            "priority": "recommended",
            "imm_form_reference": None,
            "sort_order": 4,
        },
        {
            "document_type": "travel",
            "document_name": "Itinéraire de voyage",
            "description": "Réservations de vol (aller-retour) et hébergement",
            "priority": "recommended",
            "imm_form_reference": None,
            "sort_order": 5,
        },
        {
            "document_type": "other",
            "document_name": "Lettre d'invitation",
            "description": "Si invité par un résident/citoyen canadien",
            "priority": "optional",
            "imm_form_reference": None,
            "sort_order": 6,
        },
        {
            "document_type": "ties",
            "document_name": "Preuves d'attaches au pays",
            "description": "Titre de propriété, inscription scolaire des enfants, entreprise, etc.",
            "priority": "recommended",
            "imm_form_reference": None,
            "sort_order": 7,
        },
        {
            "document_type": "form",
            "document_name": "Formulaire IMM 5257",
            "description": "Demande de visa de résident temporaire",
            "priority": "mandatory",
            "imm_form_reference": "IMM 5257",
            "sort_order": 8,
        },
        {
            "document_type": "form",
            "document_name": "Formulaire IMM 5645 - Renseignements famille",
            "description": "Information sur les membres de la famille",
            "priority": "mandatory",
            "imm_form_reference": "IMM 5645",
            "sort_order": 9,
        },
    ],
}
